server:
  port: 8081

spring:
  datasource:
    url: ${NOTIF_DB_URL:jdbc:postgresql://localhost:5432/my_dev_db}
    username: ${NOTIF_DB_USERNAME:default_dev_user}
    password: ${NOTIF_DB_PASSWORD:default_dev_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  management:
    endpoints:
      web:
        exposure:
          include: "health,info,env,metrics,beans,mappings"
        base-path: /actuator
    endpoint:
      health:
        show-details: always
    server:
      port: 8081

  mail:
    host: ${MAILTRAP_HOST:smtp.mailtrap.io}
    port: ${MAILTRAP_PORT:587}
    username: ${MAILTRAP_USERNAME:default_mailtrap_user}
    password: ${MAILTRAP_PASSWORD:default_mailtrap_pass}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  from: no-reply@batuhanproject.com