server:
  port: 8080

spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/my_dev_db}
    username: ${AUTH_DB_USERNAME:default_dev_user}
    password: ${AUTH_DB_PASSWORD:default_dev_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SIGNING_SECRET:A_Strong_Secret_For_Dev_Only}
  expirationMs: 86400000